#!/usr/bin/env ruby
# frozen_string_literal: true

require "factory_hoist"

unless ARGV.shift == "advise"
  warn "Usage: factory_hoist advise [SPEC_PATH ...]"
  exit 1
end

FactoryHoist.advise(*ARGV)
