#!/usr/bin/env ruby
# frozen_string_literal: true

unless ARGV.shift == "advise"
  warn "Usage: factory_hoist advise [SPEC_PATH ...]"
  exit 1
end

require "rspec/core"
require "factory_hoist"

paths = ARGV.empty? ? ["spec"] : ARGV
status = RSpec::Core::Runner.run(paths)
FactoryHoist.advise(*paths)
exit status
